services:
  app_go:
    image: juliofc/desafio_grpc:latest
    ports:
      - 50051:50051
    networks:
      - desafio_network
      
  app_nestjs:
    image: juliofc/desafio_nestjs:latest    
    ports:
      - 3000:3000    
    networks:
      - desafio_network
    
networks:
  desafio_network:
    driver: bridge
    ipam:
      driver: default
       